name: Spark staging Pipeline
on:
  push:
    branches:
      - staging
env:
  LAMBDA_ENVIRONMENT: staging

jobs:
  deploy_zip:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Get Repository name
        run: echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')" >> $GITHUB_ENV
        shell: bash
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build application
        run: npm install
      - name: Removes existing .env file
        run: rm -f .env*

      - name: Get Common SSM parameters
        uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
        with:
          ssm-path: /${{ env.LAMBDA_ENVIRONMENT }}/lambda/commons/
          format: dotenv
          output: .env.${{ env.LAMBDA_ENVIRONMENT }}
      - name: Get APP Specific SSM parameters
        uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
        with:
          ssm-path: /${{ env.LAMBDA_ENVIRONMENT }}/lambda/${{env.REPOSITORY_NAME}}/
          format: dotenv
          output: .env.${{ env.LAMBDA_ENVIRONMENT }}
      - name: serverless deploy
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy --stage ${{env.LAMBDA_ENVIRONMENT}}